


#azure:
#  cosmosdb:
#    uri: vrd-dev.mongo.cosmos.azure.com:10255
#    key: kHOsnhFOpABVhr0HcF2zVo6khb38dGiRx8rLM15eoBXp13cAPXrmAWmLHEOSkN7nL8lQoHX1e1gxwSpXYnfIXg==
##    secondaryKey: U5K3jvYGlWMtOzFvOVnpdWL9M2UJnNG0qSyrFLJVwGo7AJlqG4V22kv712p2a7RcPY6H6v3mVh4Sqb7Lq9zQ6Q==
#    database: vrd-dev
##    populateQueryMetrics: true

#mybatis:
##  config-location: mybatis/sqlmap-config.xml
#  mapper-locations: mybatis/**/*.xml
#  type-aliases-package: com.skgc.vrd.techsupport.model,com.skgc.vrd.account.model






spring:
  profiles:
    active: local

---
spring:
  profiles: local

  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
#        dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true

    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate.ddl-auto: update   
     
  datasource:
#    url: jdbc:h2:./skgc-vrd-local-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
##    url: jdbc:h2:mem:skgc-vrd-local.db;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password: sa
    driverClassName: org.mariadb.jdbc.Driver 
    url: jdbc:mariadb://vrd-mariadb.mariadb.database.azure.com:3306/vrd-test?useSSL=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: vrdadmin@vrd-mariadb
    password: Admin123
#    url: jdbc:mariadb://localhost:3306/vrd-test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: dbtest1234

  data:
    mongodb:
      uri: mongodb://vrd-dev:kHOsnhFOpABVhr0HcF2zVo6khb38dGiRx8rLM15eoBXp13cAPXrmAWmLHEOSkN7nL8lQoHX1e1gxwSpXYnfIXg==@vrd-dev.mongo.cosmos.azure.com:10255/?ssl=true&retryWrites=false&replicaSet=globaldb
#      host: vrd-dev.mongo.cosmos.azure.com
#      port: 10255
      database: vrd-dev
#      username: vrd-dev   
#      password: kHOsnhFOpABVhr0HcF2zVo6khb38dGiRx8rLM15eoBXp13cAPXrmAWmLHEOSkN7nL8lQoHX1e1gxwSpXYnfIXg== 
  redis:
    lettuce:
       pool:
         max-active: 10
         max-idle: 10
         min-idle: 2
    host: 40.82.136.153
    port: 6379
    password: vrd1234

  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
      
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE 

# App Properties
sam-backend:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000 
     
server.port: 8888  

# sendgrid Email API
sendgrid:
  apikey: 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
  valid-mime-types: #이메일 첨부파일로 가능한 파일 mime 타입
    - image
    - application/pdf
    - application/vnd.openxmlformats-officedocument
    - application/vnd.ms
  max-send: 500 #한번에 최대 전송 가능한 메일 숫자
  break-second : 30 # max-send 이상의 메일 전송시 sleep second
  