apiVersion: v1
kind: ConfigMap
metadata:
  name: sam-backend-configmap
data:
  application-dev.yaml: |-
    management:
      endpoint:
        restart:
          enabled: true
        health:
          enabled: true
        info:
          enabled: true
      endpoints:
        web:
          exposure:
            include: health,metrics
    
    spring:
      jpa:
        properties:
          hibernate:
            jdbc.lob.non_contextual_creation: true
            # The SQL dialect makes Hibernate generate better SQL for the chosen database
            dialect: org.hibernate.dialect.MariaDBDialect
            show_sql: true
    
        # Hibernate ddl auto (create, create-drop, validate, update)
        hibernate.ddl-auto: update    
        
      datasource:
        driverClassName: org.mariadb.jdbc.Driver 
        url: jdbc:mariadb://vrd-dev.mariadb.database.azure.com:3306/vrd-test?useSSL=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: ${MARIADB_USERNAME}
        password: ${MARIADB_PASSWORD}
      data:
        mongodb:
          uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@vrd-dev.mongo.cosmos.azure.com:10255/?ssl=true&retryWrites=false #&replicaSet=globaldb
          database: vrd-dev
      redis:
        lettuce:
           pool:
             max-active: 10
             max-idle: 10
             min-idle: 2
        host: 40.82.136.153
        port: 6379
        password: ${REDIS_PASSWORD}
    
    # App Properties
    sam-backend:
      app:
        jwtSecret: ${JWT_SECRET}
        jwtExpirationMs: 86400000 
                
    server.port: 8080