apiVersion: apps/v1
kind: Deployment
metadata:
  name: sam-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sam-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: sam-backend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: sam-backend
        image: bekube/sam-backend:latest
        imagePullPolicy: Always
        args: ["--spring.profiles.active=dev","--spring.config.location=/deployments/config/application-dev.yaml"]
        ports:
        - containerPort: 8080
        env:
        - name: MARIADB_USERNAME
          valueFrom:
            secretKeyRef:
              name: sam-backend-secretmap
              key: mariadb-username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sam-backend-secretmap
              key: mariadb-password
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: sam-backend-secretmap
              key: mongodb-username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sam-backend-secretmap
              key: mongodb-password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sam-backend-secretmap
              key: redis-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: sam-backend-secretmap
              key: jwt-secret
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1  
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        volumeMounts:
          - name: config
            mountPath: "/deployments/config"
            readOnly: true
                          
      volumes:
        - name: config
          configMap:
            name: sam-backend-configmap
            items:
              - key: application-dev.yaml
                path: application-dev.yaml