apiVersion: apps/v1
kind: Deployment
metadata:
  name: sam-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sam-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: sam-backend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: sam-backend
        image: bekube/sam-backend:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
